# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b79c6362c62a0543ff2f08d24257b7b9946a1d03bc49ff4bc3bb6d26a8a84ea1ace690865e85f7df2e0b849aa123c1e349aaa47f562356335f34cd2ef8dcc21e

test:
  secret_key_base: ebb135627eba30d943b3ec27b75fdfb39301c89ab390ae51b787b934c2fe15456565c783f8cdebde0b0cd678020bcb7140c589daf9c4fbcbb0ffca4a28469f04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
